# --- mappings.py (FINAL VERSION) ---

device_profile_name_map = {
    'GS4220E': 'CX_ROUTER',
    'GS2029E': 'CX_ROUTER',
    'GS4227E': 'CX_ROUTER',
    'GS5239E': 'CX_ROUTER',
    'GS2128XG': 'ONT',
    'GS2028E': 'CX_ROUTER',
    'GM1028': 'CX_MESH',
    'GM1028H': 'CX_MESH',
    'GPR2032H': 'CX_MESH',
    'XGS': 'CX_MESH',
    'GM2037': 'CX_MESH',
    'GS4227W': 'ONT',
    'GS4227': 'ONT',
    '803G': 'ONT',
    '812G': 'ONT',
    '716GE': 'ONT',
    'GP1100X': 'ONT',
    'GP1101X': 'ONT',
    'GS4237': 'ONT',
    '717GE': 'ONT',
    'GS5229XG': 'ONT',
    'GPR8802X': 'ONT',
    'GP4200XH': 'ONT',
    'GP4201X': 'ONT',
    'GS5229E': 'CX_ROUTER',
    'GS4229E': 'CX_ROUTER',
    'G1001-C': 'GAM_COAX_ENDPOINT',
    'SFP-XGS': 'CX_SFP',
    'SFP-GPON': 'CX_SFP',
    'GP1100G': 'ONT',
    'GS5239XG': 'ONT',
    'GPR2022H-ONT': 'ONT',
    'GPR1027E': 'CX_ROUTER',
}

device_numbers_template_map = {
    # --- Routers, Mesh, etc. (no change) ---
    'GS4220E': 'MAC=<<MAC>>|SN=<<SN>>|ROUTER_FSAN=<<FSAN>>',
    'GS4227E': 'MAC=<<MAC>>|SN=<<SN>>|ROUTER_FSAN=<<FSAN>>',
    'GS2028E': 'MAC=<<MAC>>|SN=<<SN>>|ROUTER_FSAN=<<FSAN>>',
    'GS2029E': 'MAC=<<MAC>>|SN=<<SN>>|ROUTER_FSAN=<<FSAN>>',
    'GM1028': 'MAC=<<MAC>>|SN=<<SN>>|MESH_FSAN=<<FSAN>>',
    'GM1028H': 'MAC=<<MAC>>|SN=<<SN>>|MESH_FSAN=<<FSAN>>',
    'GPR2032H': 'MAC=<<MAC>>|SN=<<SN>>|MESH_FSAN=<<FSAN>>',
    'XGS': 'MAC=<<MAC>>|SN=<<SN>>|MESH_FSAN=<<FSAN>>',
    'GM2037': 'MAC=<<MAC>>|SN=<<SN>>|MESH_FSAN=<<FSAN>>',
    'G1001-C': 'MAC=<<MAC>>|SN=<<SN>>',
    'SFP-XGS': 'MAC=<<MAC>>|SN=<<SN>>|SIP_FSAN=<<FSAN>>',
    'SFP-GPON': 'MAC=<<MAC>>|SN=<<SN>>|SIP_FSAN=<<FSAN>>',
    'GS5229E': 'MAC=<<MAC>>|SN=<<SN>>|ROUTER_FSAN=<<FSAN>>',
    'GS4229E': 'MAC=<<MAC>>|SN=<<SN>>|ROUTER_FSAN=<<FSAN>>',
    'GPR1027E': 'MAC=<<MAC>>|SN=<<SN>>|MESH_FSAN=<<FSAN>>',

    # --- ONTs (with _ALT versions) ---
    'GS2128XG': 'MAC=<<MAC>>|SN=<<SN>>|ONT_FSAN=<<FSAN>>|ONT_ID=no value|ONT_NODENAME=no value|ONT_PORT=G1|ONT_PROFILE_ID=GS4227|ONT_MOMENTUM_PASSWORD=no value',
    'GS2128XG_ALT': 'ONT_FSAN=<<FSAN>>|ONT_ID=no value|ONT_NODENAME=no value|ONT_PORT=G1|ONT_PROFILE_ID=GS4227|ONT_MOMENTUM_PASSWORD=no value',

    'GS4227W': 'MAC=<<MAC>>|SN=<<SN>>|ONT_FSAN=<<FSAN>>|ONT_ID=no value|ONT_NODENAME=no value|ONT_PORT=G1|ONT_PROFILE_ID=GS4227|ONT_MOMENTUM_PASSWORD=no value',
    'GS4227W_ALT': 'ONT_FSAN=<<FSAN>>|ONT_ID=no value|ONT_NODENAME=no value|ONT_PORT=G1|ONT_PROFILE_ID=GS4227|ONT_MOMENTUM_PASSWORD=no value',

    'GS4227': 'MAC=<<MAC>>|SN=<<SN>>|ONT_FSAN=<<FSAN>>|ONT_ID=no value|ONT_NODENAME=no value|ONT_PORT=G1|ONT_PROFILE_ID=GS4227|ONT_MOMENTUM_PASSWORD=no value',
    'GS4227_ALT': 'ONT_FSAN=<<FSAN>>|ONT_ID=no value|ONT_NODENAME=no value|ONT_PORT=G1|ONT_PROFILE_ID=GS4227|ONT_MOMENTUM_PASSWORD=no value',

    '803G': 'MAC=<<MAC>>|SN=<<SN>>|ONT_FSAN=<<FSAN>>|ONT_ID=no value|ONT_NODENAME=no value|ONT_PORT=1|ONT_PROFILE_ID=803_G|ONT_MOMENTUM_PASSWORD=no value',
    '803G_ALT': 'ONT_FSAN=<<FSAN>>|ONT_ID=no value|ONT_NODENAME=no value|ONT_PORT=1|ONT_PROFILE_ID=803_G|ONT_MOMENTUM_PASSWORD=no value',

    '812G': 'MAC=<<MAC>>|SN=<<SN>>|ONT_FSAN=<<FSAN>>|ONT_ID=no value|ONT_NODENAME=no value|ONT_PORT=1|ONT_PROFILE_ID=812G|ONT_MOMENTUM_PASSWORD=no value',
    '812G_ALT': 'ONT_FSAN=<<FSAN>>|ONT_ID=no value|ONT_NODENAME=no value|ONT_PORT=1|ONT_PROFILE_ID=812G|ONT_MOMENTUM_PASSWORD=no value',

    '716GE': 'MAC=<<MAC>>|SN=<<SN>>|ONT_FSAN=<<FSAN>>|ONT_ID=no value|ONT_NODENAME=no value|ONT_PORT=1|ONT_PROFILE_ID=139|ONT_MOMENTUM_PASSWORD=no value',
    '716GE_ALT': 'ONT_FSAN=<<FSAN>>|ONT_ID=no value|ONT_NODENAME=no value|ONT_PORT=1|ONT_PROFILE_ID=139|ONT_MOMENTUM_PASSWORD=no value',

    'GP1100X': 'MAC=<<MAC>>|SN=<<SN>>|ONT_FSAN=<<FSAN>>|ONT_ID=no value|ONT_NODENAME=no value|ONT_PORT=x1|ONT_PROFILE_ID=GP1100X|ONT_MOMENTUM_PASSWORD=no value',
    'GP1100X_ALT': 'ONT_FSAN=<<FSAN>>|ONT_ID=no value|ONT_NODENAME=no value|ONT_PORT=x1|ONT_PROFILE_ID=GP1100X|ONT_MOMENTUM_PASSWORD=no value',

    'GP1101X': 'MAC=<<MAC>>|SN=<<SN>>|ONT_FSAN=<<FSAN>>|ONT_ID=no value|ONT_NODENAME=no value|ONT_PORT=x1|ONT_PROFILE_ID=GP1101X|ONT_MOMENTUM_PASSWORD=no value',
    'GP1101X_ALT': 'ONT_FSAN=<<FSAN>>|ONT_ID=no value|ONT_NODENAME=no value|ONT_PORT=x1|ONT_PROFILE_ID=GP1101X|ONT_MOMENTUM_PASSWORD=no value',

    'GS4237': 'MAC=<<MAC>>|SN=<<SN>>|ONT_FSAN=<<FSAN>>|ONT_ID=no value|ONT_NODENAME=no value|ONT_PORT=G1|ONT_PROFILE_ID=GS4237|ONT_MOMENTUM_PASSWORD=no value',
    'GS4237_ALT': 'ONT_FSAN=<<FSAN>>|ONT_ID=no value|ONT_NODENAME=no value|ONT_PORT=G1|ONT_PROFILE_ID=GS4237|ONT_MOMENTUM_PASSWORD=no value',

    '717GE': 'MAC=<<MAC>>|SN=<<SN>>|ONT_FSAN=<<FSAN>>|ONT_ID=no value|ONT_NODENAME=no value|ONT_PORT=1|ONT_PROFILE_ID=717GE|ONT_MOMENTUM_PASSWORD=no value',
    '717GE_ALT': 'ONT_FSAN=<<FSAN>>|ONT_ID=no value|ONT_NODENAME=no value|ONT_PORT=1|ONT_PROFILE_ID=717GE|ONT_MOMENTUM_PASSWORD=no value',

    'GS5229XG': 'MAC=<<MAC>>|SN=<<SN>>|ONT_FSAN=<<FSAN>>|ONT_ID=no value|ONT_NODENAME=no value|ONT_PORT=G1|ONT_PROFILE_ID=GS5229XG|ONT_MOMENTUM_PASSWORD=no value',
    'GS5229XG_ALT': 'ONT_FSAN=<<FSAN>>|ONT_ID=no value|ONT_NODENAME=no value|ONT_PORT=G1|ONT_PROFILE_ID=GS5229XG|ONT_MOMENTUM_PASSWORD=no value',

    'GPR8802X': 'MAC=<<MAC>>|SN=<<SN>>|ONT_FSAN=<<FSAN>>|ONT_ID=no value|ONT_NODENAME=no value|ONT_PORT=G1|ONT_PROFILE_ID=GPR8802X|ONT_MOMENTUM_PASSWORD=no value',
    'GPR8802X_ALT': 'ONT_FSAN=<<FSAN>>|ONT_ID=no value|ONT_NODENAME=no value|ONT_PORT=G1|ONT_PROFILE_ID=GPR8802X|ONT_MOMENTUM_PASSWORD=no value',

    'GP4200XH': 'MAC=<<MAC>>|SN=<<SN>>|ONT_FSAN=<<FSAN>>|ONT_ID=no value|ONT_NODENAME=no value|ONT_PORT=1|ONT_PROFILE_ID=GP4200XH|ONT_MOMENTUM_PASSWORD=no value',
    'GP4200XH_ALT': 'ONT_FSAN=<<FSAN>>|ONT_ID=no value|ONT_NODENAME=no value|ONT_PORT=1|ONT_PROFILE_ID=GP4200XH|ONT_MOMENTUM_PASSWORD=no value',

    'GP4201X': 'MAC=<<MAC>>|SN=<<SN>>|ONT_FSAN=<<FSAN>>|ONT_ID=no value|ONT_NODENAME=no value|ONT_PORT=1|ONT_PROFILE_ID=GP4201X|ONT_MOMENTUM_PASSWORD=no value',
    'GP4201X_ALT': 'ONT_FSAN=<<FSAN>>|ONT_ID=no value|ONT_NODENAME=no value|ONT_PORT=1|ONT_PROFILE_ID=GP4201X|ONT_MOMENTUM_PASSWORD=no value',

    'GP1100G': 'MAC=<<MAC>>|SN=<<SN>>|ONT_FSAN=<<FSAN>>|ONT_ID=no value|ONT_NODENAME=no value|ONT_PORT=G1|ONT_PROFILE_ID=GP1100G|ONT_MOMENTUM_PASSWORD=no value',
    'GP1100G_ALT': 'ONT_FSAN=<<FSAN>>|ONT_ID=no value|ONT_NODENAME=no value|ONT_PORT=G1|ONT_PROFILE_ID=GP1100G|ONT_MOMENTUM_PASSWORD=no value',

    'GS5239XG': 'MAC=<<MAC>>|SN=<<SN>>|ONT_FSAN=<<FSAN>>|ONT_ID=no value|ONT_NODENAME=no value|ONT_PORT=G1|ONT_PROFILE_ID=GS5239XG|ONT_MOMENTUM_PASSWORD=no value',
    'GS5239XG_ALT': 'ONT_FSAN=<<FSAN>>|ONT_ID=no value|ONT_NODENAME=no value|ONT_PORT=G1|ONT_PROFILE_ID=GS5239XG|ONT_MOMENTUM_PASSWORD=no value',

    'GPR2022H-ONT': 'MAC=<<MAC>>|SN=<<SN>>|ONT_FSAN=<<FSAN>>|ONT_ID=no value|ONT_NODENAME=no value|ONT_PORT=G1|ONT_PROFILE_ID=GPR2022H|ONT_MOMENTUM_PASSWORD=no value',
    'GPR2022H-ONT_ALT': 'ONT_FSAN=<<FSAN>>|ONT_ID=no value|ONT_NODENAME=no value|ONT_PORT=G1|ONT_PROFILE_ID=GPR2022H|ONT_MOMENTUM_PASSWORD=no value',
}
